Feature/ban user
tryanzu/frontend pull request #13
Opened 2019-06-04 17:24 UTC by Bolillin

feat: Modal's Ban a user asking from a list of reasons.

2019-06-04 18:12 UTC, fernandez14 requested changes
Las razones de cancelación, ¿podrías ponerlas envueltas en un select y los options siendo la razón en cuestión?

Cuando seleccione otros, tiene que aparecer un textarea para escribir los motivos también

2019-06-05 16:27 UTC, RodrigoCR commented on src/board/components/actions.js
> +                                    placeholder: t`ej. Por burro`,
No escribas groserías por favor

2019-06-05 16:28 UTC, RodrigoCR commented on src/board/components/actions.js
> +                                    option('.menu-item', t`Otro`),
Creo que te recomendaría crear las razones en un array, y luego usar:
```reasons.map(reason => (
option('.menu-item', reason)
)
```
O algo así, para que después podamos hacer que las razones vengan de un endpoint, y no tener que estar modificando el front para esto.

2019-06-05 16:30 UTC, RodrigoCR commented
Ah chingá, ya ni sé usar Github :v...

Creo que te recomendaría crear las razones en un array, y luego usar:
```javascript
reasons.map(reason => (
option('.menu-item', reason)
)
```
O algo así, para que después podamos hacer que las razones vengan de un endpoint, y no tener que estar modificando el front para esto.

2019-06-05 17:15 UTC, Bolillin commented
Ya quedo RodrigoCR, gracias por el tip

2019-06-11 23:55 UTC, merged