Feature/replace tachyons colours2
tryanzu/frontend pull request #41
Opened 2019-11-20 21:37 UTC by Bolillin

Ya quedaron reemplazados los colores de tachyons.

2019-11-25 19:43 UTC, fernandez14 requested changes

2019-11-25 19:43 UTC, fernandez14 commented on src/themes/autumn/_common.scss
> +.error-message{
no podemos reutilizar las variables y/o una clase de color de spectree?

Tanto para subtext como para error-message

2019-11-25 20:23 UTC, Bolillin commented on src/themes/autumn/_common.scss
> +.error-message{
Cierto, no me habia acordado de spectre.
Puedo eliminar la clase de "subtext" (#acb3c2) y en los components cambiar esa clase por "text-gray" (bcc3ce). El color es muy similar.
![image](https://user-images.githubusercontent.com/31712515/69573709-470b9180-0f8c-11ea-80a1-8c39b0ec723d.png)
Creo que se podria cambiar por esa clase si es que en el dark theme se ocupa el mismo color en esos elementos, si no, considero que seria mejor dejar la clase porque asi cuando se desarrolle el drak theme solo se tendría que cambiar el color de esa clase.

En error-message se puede reutilizar una clase de spectre llamada "bg-error", el estilo final no seria el mismo por el color de fondo y el color del texto. Pero aquí considero que si se podría reutilizar esta clase (si no importa cambiar un poco el diseño original), pues aunque esté habilitado el dark theme, considero que este estilo no se tendría que modificar, ya que es un mensaje de error y ya tiene contraste por si mismo.
![image](https://user-images.githubusercontent.com/31712515/69574685-660b2300-0f8e-11ea-80a8-9fb582503aa6.png)

2019-11-25 22:46 UTC, fernandez14 requested changes

2019-11-25 22:46 UTC, fernandez14 commented on src/themes/autumn/_common.scss
> +	color: #999999;
podemos usar una variable de spectree para esto también?

2019-11-25 22:58 UTC, Bolillin commented on src/themes/autumn/_common.scss
> +	color: #999999;
Aqui si no hay un color muy parecido, pero igual podria ser con text-gray.

2019-11-26 00:12 UTC, fernandez14 approved these changes

2019-11-26 00:12 UTC, merged